INSERT INTO dewey (code, label) VALUES('090', 'Manuscrits et livres rares');
INSERT INTO dewey (code, label) VALUES('190', 'Philosophie occidentale moderne');
INSERT INTO dewey (code, label) VALUES('080', 'Recueils généraux');
INSERT INTO dewey (code, label) VALUES('290', 'Religion comparée. Autres religions');
INSERT INTO dewey (code, label) VALUES('180', 'Philosophie antique, médiévale, orientale');
INSERT INTO dewey (code, label) VALUES('070', 'Journalisme, édition. Journaux');
INSERT INTO dewey (code, label) VALUES('390', 'Coutumes, savoir-vivre, folklore');
INSERT INTO dewey (code, label) VALUES('280', 'Confessions et sectes chrétiennes');
INSERT INTO dewey (code, label) VALUES('170', 'Ethique');
INSERT INTO dewey (code, label) VALUES('060', 'Organisations générales et muséologie');
INSERT INTO dewey (code, label) VALUES('181', 'Philosophies de l''Orient');
INSERT INTO dewey (code, label) VALUES('490', 'Autres langues');
INSERT INTO dewey (code, label) VALUES('380', 'Commerce, communications, transports');
INSERT INTO dewey (code, label) VALUES('270', 'Histoire et géographie de l''Eglise');
INSERT INTO dewey (code, label) VALUES('160', 'Logique');
INSERT INTO dewey (code, label) VALUES('050', 'Publications en série d''ordre général');
INSERT INTO dewey (code, label) VALUES('590', 'Zoologie');
INSERT INTO dewey (code, label) VALUES('480', 'Langues helléniques. Grec');
INSERT INTO dewey (code, label) VALUES('370', 'Education');
INSERT INTO dewey (code, label) VALUES('260', 'Théologie et société');
INSERT INTO dewey (code, label) VALUES('150', 'Psychologie');
INSERT INTO dewey (code, label) VALUES('690', 'Bâtiment');
INSERT INTO dewey (code, label) VALUES('580', 'Botanique');
INSERT INTO dewey (code, label) VALUES('470', 'Langues italiques. Latin');
INSERT INTO dewey (code, label) VALUES('360', 'Problèmes et services sociaux. Associations');
INSERT INTO dewey (code, label) VALUES('250', 'Eglise locale et ordres religieux');
INSERT INTO dewey (code, label) VALUES('140', 'Les divers systèmes philosophiques');
INSERT INTO dewey (code, label) VALUES('030', 'Encyclopédies générales');
INSERT INTO dewey (code, label) VALUES('790', 'Loisirs et arts du spectacle');
INSERT INTO dewey (code, label) VALUES('680', 'Fabrications pour utilisations spécifiques');
INSERT INTO dewey (code, label) VALUES('570', 'Sciences de la vie');
INSERT INTO dewey (code, label) VALUES('460', 'Langues espagnole et portugaise');
INSERT INTO dewey (code, label) VALUES('350', 'Administration publique');
INSERT INTO dewey (code, label) VALUES('240', 'Théologie morale et spirituelle');
INSERT INTO dewey (code, label) VALUES('130', 'Phénomènes paranormaux. Pseudo-sciences');
INSERT INTO dewey (code, label) VALUES('020', 'Bibliothéconomie et sciences de l''information');
INSERT INTO dewey (code, label) VALUES('890', 'Littératures des autres langues');
INSERT INTO dewey (code, label) VALUES('780', 'Musique');
INSERT INTO dewey (code, label) VALUES('670', 'Fabrication industrielle');
INSERT INTO dewey (code, label) VALUES('560', 'Paléontologie. Paléozoologie');
INSERT INTO dewey (code, label) VALUES('450', 'Italien, roumain, rhéto-romain');
INSERT INTO dewey (code, label) VALUES('340', 'Droit');
INSERT INTO dewey (code, label) VALUES('230', 'Théologie doctrinale chrétienne');
INSERT INTO dewey (code, label) VALUES('120', 'Epistémologie, causalité, genre humain');
INSERT INTO dewey (code, label) VALUES('010', 'Bibliographies');
INSERT INTO dewey (code, label) VALUES('990', 'Histoire générale des autres pays');
INSERT INTO dewey (code, label) VALUES('880', 'Littératures helléniques. Littérature grecque');
INSERT INTO dewey (code, label) VALUES('770', 'Photographie et photographies');
INSERT INTO dewey (code, label) VALUES('660', 'Techniques chimiques et techniques connexes');
INSERT INTO dewey (code, label) VALUES('550', 'Sciences de la Terre et des autres mondes');
INSERT INTO dewey (code, label) VALUES('440', 'Langues romanes. Français');
INSERT INTO dewey (code, label) VALUES('330', 'Economie');
INSERT INTO dewey (code, label) VALUES('220', 'Bible');
INSERT INTO dewey (code, label) VALUES('110', 'Métaphysique');
INSERT INTO dewey (code, label) VALUES('000', 'Généralités');
INSERT INTO dewey (code, label) VALUES('980', 'Histoire générale de l''Amérique du Sud');
INSERT INTO dewey (code, label) VALUES('870', 'Littératures des langues italiques. Littérature latine');
INSERT INTO dewey (code, label) VALUES('760', 'Arts graphiques. Gravures');
INSERT INTO dewey (code, label) VALUES('650', 'Gestion et services connexes');
INSERT INTO dewey (code, label) VALUES('540', 'Chimie et sciences connexes');
INSERT INTO dewey (code, label) VALUES('430', 'Langues germaniques. Allemand');
INSERT INTO dewey (code, label) VALUES('320', 'Science politique');
INSERT INTO dewey (code, label) VALUES('210', 'Religion naturelle');
INSERT INTO dewey (code, label) VALUES('100', 'Philosophie et disciplines connexes');
INSERT INTO dewey (code, label) VALUES('970', 'Histoire générale rie l''Amérique du Nord');
INSERT INTO dewey (code, label) VALUES('860', 'Littératures espagnole et portugaise');
INSERT INTO dewey (code, label) VALUES('750', 'La peinture et les peintures');
INSERT INTO dewey (code, label) VALUES('640', 'Economie domestique. Vie à la maison');
INSERT INTO dewey (code, label) VALUES('530', 'Physique');
INSERT INTO dewey (code, label) VALUES('420', 'Langue anglaise. Anglo-saxon');
INSERT INTO dewey (code, label) VALUES('310', 'Statistiques');
INSERT INTO dewey (code, label) VALUES('200', 'Religion');
INSERT INTO dewey (code, label) VALUES('189', 'Philosophie médiévale occidentale');
INSERT INTO dewey (code, label) VALUES('960', 'Histoire générale de l''Afrique');
INSERT INTO dewey (code, label) VALUES('850', 'Littératures italienne, roumaine, rhéto-romane');
INSERT INTO dewey (code, label) VALUES('740', 'Dessin, arts décoratifs et mineurs');
INSERT INTO dewey (code, label) VALUES('630', 'Agriculture et techniques connexes');
INSERT INTO dewey (code, label) VALUES('520', 'Astronomie et sciences connexes');
INSERT INTO dewey (code, label) VALUES('410', 'Linguistique');
INSERT INTO dewey (code, label) VALUES('300', 'Sciences sociales');
INSERT INTO dewey (code, label) VALUES('443', 'Dictionnaires du français standard');
INSERT INTO dewey (code, label) VALUES('950', 'Histoire générale de l''Asie');
INSERT INTO dewey (code, label) VALUES('840', 'Littératures des langues romanes. Littérature française');
INSERT INTO dewey (code, label) VALUES('730', 'Arts plastiques. Sculpture');
INSERT INTO dewey (code, label) VALUES('620', 'Art de l''ingénieur et activités connexes');
INSERT INTO dewey (code, label) VALUES('510', 'Mathématiques');
INSERT INTO dewey (code, label) VALUES('400', 'Langues');
INSERT INTO dewey (code, label) VALUES('301', 'Anthropologie et sociologie');
INSERT INTO dewey (code, label) VALUES('940', 'Histoire générale de l''Europe');
INSERT INTO dewey (code, label) VALUES('830', 'Littératures des langues germaniques');
INSERT INTO dewey (code, label) VALUES('720', 'Architecture');
INSERT INTO dewey (code, label) VALUES('610', 'Sciences médicales. Médecine');
INSERT INTO dewey (code, label) VALUES('500', 'Sciences de la nature et mathématiques');
INSERT INTO dewey (code, label) VALUES('930', 'Histoire générale du monde ancien');
INSERT INTO dewey (code, label) VALUES('820', 'Littératures anglaise et anglo-saxonne');
INSERT INTO dewey (code, label) VALUES('710', 'Urbanisme. Art du paysage');
INSERT INTO dewey (code, label) VALUES('600', 'Technique (Sciences appliquées)');
INSERT INTO dewey (code, label) VALUES('920', 'Biographie générale et généalogie');
INSERT INTO dewey (code, label) VALUES('810', 'Littérature américaine en anglais');
INSERT INTO dewey (code, label) VALUES('700', 'Les arts');
INSERT INTO dewey (code, label) VALUES('821', 'Poésie de langue anglaise');
INSERT INTO dewey (code, label) VALUES('403', 'Concordances, dictionnaires, encyclopédies');
INSERT INTO dewey (code, label) VALUES('910', 'Géographie générale. Voyages');
INSERT INTO dewey (code, label) VALUES('800', 'Littérature (Belles-lettres)');
INSERT INTO dewey (code, label) VALUES('822', 'Littérature dramatique anglaise');
INSERT INTO dewey (code, label) VALUES('823', 'Fiction anglaise');
INSERT INTO dewey (code, label) VALUES('944', 'Histoire de la France (depuis 486)');
INSERT INTO dewey (code, label) VALUES('306', 'Culture, institutions sociales');
INSERT INTO dewey (code, label) VALUES('900', 'Géographie, histoire, sciences auxiliaires de l''histoire');
