INSERT INTO role ( id, label, creator, url ) VALUES( 10, 'Adaptateur', NULL, 'http://id.loc.gov/vocabulary/relators/adp' );
INSERT INTO role ( id, label, creator, url ) VALUES( 20, 'Agence de publicité', NULL, 'http://id.loc.gov/vocabulary/relators/org' );
INSERT INTO role ( id, label, creator, url ) VALUES( 30, 'Agence photographique', NULL, 'http://id.loc.gov/vocabulary/relators/org' );
INSERT INTO role ( id, label, creator, url ) VALUES( 40, 'Annotateur', NULL, 'http://id.loc.gov/vocabulary/relators/ann' );
INSERT INTO role ( id, label, creator, url ) VALUES( 50, 'Arrangeur', NULL, 'http://id.loc.gov/vocabulary/relators/arr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 60, 'Notice bibliographique', NULL, 'http://id.loc.gov/vocabulary/relators/ann' );
INSERT INTO role ( id, label, creator, url ) VALUES( 80, 'Auteur de l’argument', NULL, 'http://id.loc.gov/vocabulary/relators/lbt' );
INSERT INTO role ( id, label, creator, url ) VALUES( 90, 'Auteur de l’animation', NULL, 'http://id.loc.gov/vocabulary/relators/anm' );
INSERT INTO role ( id, label, creator, url ) VALUES( 100, 'Auteur de l’idée originale', NULL, 'http://id.loc.gov/vocabulary/relators/ccp' );
INSERT INTO role ( id, label, creator, url ) VALUES( 110, 'Auteur de lettres', NULL, 'http://id.loc.gov/vocabulary/relators/aut' );
INSERT INTO role ( id, label, creator, url ) VALUES( 120, 'Auteur du commentaire', NULL, 'http://id.loc.gov/vocabulary/relators/cwt' );
INSERT INTO role ( id, label, creator, url ) VALUES( 130, 'Auteur du matériel d’accompagnement', NULL, 'http://id.loc.gov/vocabulary/relators/wam' );
INSERT INTO role ( id, label, creator, url ) VALUES( 140, 'Calligraphe', NULL, 'http://id.loc.gov/vocabulary/relators/cll' );
INSERT INTO role ( id, label, creator, url ) VALUES( 150, 'Cartographe', NULL, 'http://id.loc.gov/vocabulary/relators/ctg' );
INSERT INTO role ( id, label, creator, url ) VALUES( 160, 'Chorégraphe', NULL, 'http://id.loc.gov/vocabulary/relators/chr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 170, 'Contributeur', NULL, 'http://id.loc.gov/vocabulary/relators/clb' );
INSERT INTO role ( id, label, creator, url ) VALUES( 180, 'Collecteur', NULL, 'http://id.loc.gov/vocabulary/relators/col' );
INSERT INTO role ( id, label, creator, url ) VALUES( 190, 'Commanditaire du contenu', NULL, 'http://id.loc.gov/vocabulary/relators/spn' );
INSERT INTO role ( id, label, creator, url ) VALUES( 200, 'Commissaire d’exposition', NULL, 'http://id.loc.gov/vocabulary/relators/cur' );
INSERT INTO role ( id, label, creator, url ) VALUES( 210, 'Compilateur', NULL, 'http://id.loc.gov/vocabulary/relators/com' );
INSERT INTO role ( id, label, creator, url ) VALUES( 220, 'Compositeur', NULL, 'http://id.loc.gov/vocabulary/relators/cmp' );
INSERT INTO role ( id, label, creator, url ) VALUES( 230, 'Concepteur', NULL, 'http://id.loc.gov/vocabulary/relators/ccp' );
INSERT INTO role ( id, label, creator, url ) VALUES( 240, 'Chef de projet informatique', NULL, 'http://id.loc.gov/vocabulary/relators/prg' );
INSERT INTO role ( id, label, creator, url ) VALUES( 250, 'Conseiller scientifique', NULL, 'http://id.loc.gov/vocabulary/relators/sad' );
INSERT INTO role ( id, label, creator, url ) VALUES( 260, 'Continuateur', NULL, 'http://id.loc.gov/vocabulary/relators/ctb' );
INSERT INTO role ( id, label, creator, url ) VALUES( 270, 'Copiste', NULL, 'http://id.loc.gov/vocabulary/relators/scr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 280, 'Correcteur', NULL, 'http://id.loc.gov/vocabulary/relators/crr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 290, 'Dédicataire', NULL, 'http://id.loc.gov/vocabulary/relators/dte' );
INSERT INTO role ( id, label, creator, url ) VALUES( 300, 'Dédicateur', NULL, 'http://id.loc.gov/vocabulary/relators/dto' );
INSERT INTO role ( id, label, creator, url ) VALUES( 310, 'Dessinateur', NULL, 'http://id.loc.gov/vocabulary/relators/drm' );
INSERT INTO role ( id, label, creator, url ) VALUES( 320, 'Destinataire de lettres', NULL, 'http://id.loc.gov/vocabulary/relators/rcp' );
INSERT INTO role ( id, label, creator, url ) VALUES( 330, 'Directeur de publication', NULL, 'http://id.loc.gov/vocabulary/relators/pbd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 340, 'Dialoguiste', 1, 'http://id.loc.gov/vocabulary/relators/aud' );
INSERT INTO role ( id, label, creator, url ) VALUES( 350, 'Dramaturge', NULL, 'http://id.loc.gov/vocabulary/relators/prd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 360, 'Éditeur scientifique', NULL, 'http://id.loc.gov/vocabulary/relators/edt' );
INSERT INTO role ( id, label, creator, url ) VALUES( 370, 'Autorité émettrice de monnaie', NULL, 'http://id.loc.gov/vocabulary/relators/org' );
INSERT INTO role ( id, label, creator, url ) VALUES( 380, 'Graphiste', NULL, 'http://id.loc.gov/vocabulary/relators/art' );
INSERT INTO role ( id, label, creator, url ) VALUES( 390, 'Géodésien', NULL, 'http://id.loc.gov/vocabulary/relators/srv' );
INSERT INTO role ( id, label, creator, url ) VALUES( 400, 'Géomètre-arpenteur', NULL, 'http://id.loc.gov/vocabulary/relators/srv' );
INSERT INTO role ( id, label, creator, url ) VALUES( 410, 'Graveur', NULL, 'http://id.loc.gov/vocabulary/relators/egr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 420, 'Graveur en lettres', NULL, 'http://id.loc.gov/vocabulary/relators/egr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 430, 'Harmonisateur', NULL, 'http://id.loc.gov/vocabulary/relators/arr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 440, 'Illustrateur', 1, 'http://id.loc.gov/vocabulary/relators/ill' );
INSERT INTO role ( id, label, creator, url ) VALUES( 450, 'Interviewer', NULL, 'http://id.loc.gov/vocabulary/relators/ivr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 460, 'Reportage', NULL, 'http://id.loc.gov/vocabulary/relators/rpt' );
INSERT INTO role ( id, label, creator, url ) VALUES( 470, 'Librettiste', 1, 'http://id.loc.gov/vocabulary/relators/lbt' );
INSERT INTO role ( id, label, creator, url ) VALUES( 480, 'Lithographe', NULL, 'http://id.loc.gov/vocabulary/relators/ltg' );
INSERT INTO role ( id, label, creator, url ) VALUES( 490, 'Médailleur', NULL, 'http://id.loc.gov/vocabulary/relators/art' );
INSERT INTO role ( id, label, creator, url ) VALUES( 500, 'Metteur en scène', NULL, 'http://id.loc.gov/vocabulary/relators/rsg' );
INSERT INTO role ( id, label, creator, url ) VALUES( 510, 'Parolier', 1, 'http://id.loc.gov/vocabulary/relators/lyr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 520, 'Peintre', NULL, 'http://id.loc.gov/vocabulary/relators/art' );
INSERT INTO role ( id, label, creator, url ) VALUES( 530, 'Photographe', NULL, 'http://id.loc.gov/vocabulary/relators/pht' );
INSERT INTO role ( id, label, creator, url ) VALUES( 540, 'Postfacier', 1, 'http://id.loc.gov/vocabulary/relators/aft' );
INSERT INTO role ( id, label, creator, url ) VALUES( 550, 'Préfacier', 1, 'http://id.loc.gov/vocabulary/relators/aui' );
INSERT INTO role ( id, label, creator, url ) VALUES( 560, 'Présentateur', NULL, 'http://id.loc.gov/vocabulary/relators/ins' );
INSERT INTO role ( id, label, creator, url ) VALUES( 570, 'Producteur artistique', NULL, 'http://id.loc.gov/vocabulary/relators/drt' );
INSERT INTO role ( id, label, creator, url ) VALUES( 580, 'Producteur de fonds d’archives', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 590, 'Développeur', NULL, 'http://id.loc.gov/vocabulary/relators/prg' );
INSERT INTO role ( id, label, creator, url ) VALUES( 600, 'Programmeur', NULL, 'http://id.loc.gov/vocabulary/relators/prg' );
INSERT INTO role ( id, label, creator, url ) VALUES( 610, 'Réalisateur', 1, 'http://id.loc.gov/vocabulary/relators/rsg' );
INSERT INTO role ( id, label, creator, url ) VALUES( 620, 'Rédacteur', NULL, 'http://id.loc.gov/vocabulary/relators/red' );
INSERT INTO role ( id, label, creator, url ) VALUES( 630, 'Scénariste', 1, 'http://id.loc.gov/vocabulary/relators/aus' );
INSERT INTO role ( id, label, creator, url ) VALUES( 640, 'Sculpteur', NULL, 'http://id.loc.gov/vocabulary/relators/scl' );
INSERT INTO role ( id, label, creator, url ) VALUES( 650, 'Signataire', NULL, 'http://id.loc.gov/vocabulary/relators/sgn' );
INSERT INTO role ( id, label, creator, url ) VALUES( 660, 'Technicien graphique', NULL, 'http://id.loc.gov/vocabulary/relators/art' );
INSERT INTO role ( id, label, creator, url ) VALUES( 670, 'Testeur', NULL, 'http://id.loc.gov/vocabulary/relators/prg' );
INSERT INTO role ( id, label, creator, url ) VALUES( 680, 'Traducteur', 1, 'http://id.loc.gov/vocabulary/relators/trl' );
INSERT INTO role ( id, label, creator, url ) VALUES( 690, 'Créateur de spectacle', 1, 'http://id.loc.gov/vocabulary/relators/prf' );
INSERT INTO role ( id, label, creator, url ) VALUES( 700, 'Auteur de la collation', NULL, 'http://id.loc.gov/vocabulary/relators/scr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 710, 'Enlumineur', NULL, 'http://id.loc.gov/vocabulary/relators/ilu' );
INSERT INTO role ( id, label, creator, url ) VALUES( 720, 'Auteur de la recension', NULL, 'http://id.loc.gov/vocabulary/relators/rev' );
INSERT INTO role ( id, label, creator, url ) VALUES( 730, 'Transcripteur', NULL, 'http://id.loc.gov/vocabulary/relators/trc' );
INSERT INTO role ( id, label, creator, url ) VALUES( 740, 'Monétaire', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 750, 'Orfèvre', NULL, 'http://id.loc.gov/vocabulary/relators/art' );
INSERT INTO role ( id, label, creator, url ) VALUES( 760, 'Tailleur de coin', NULL, 'http://id.loc.gov/vocabulary/relators/art' );
INSERT INTO role ( id, label, creator, url ) VALUES( 770, 'Réalisation de la basse continue', NULL, 'http://id.loc.gov/vocabulary/relators/adp' );
INSERT INTO role ( id, label, creator, url ) VALUES( 780, 'Orchestrateur', NULL, 'http://id.loc.gov/vocabulary/relators/adp' );
INSERT INTO role ( id, label, creator, url ) VALUES( 790, 'Auteur de la réduction musicale', NULL, 'http://id.loc.gov/vocabulary/relators/adp' );
INSERT INTO role ( id, label, creator, url ) VALUES( 800, 'Auteur du slogan', NULL, 'http://id.loc.gov/vocabulary/relators/ccp' );
INSERT INTO role ( id, label, creator, url ) VALUES( 810, 'Directeur d’atelier', NULL, 'http://id.loc.gov/vocabulary/relators/mfr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 820, 'Rubricateur', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 830, 'Lettriste', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 840, 'Secrétaire', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 850, 'Notaire, tabellion', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 860, 'Greffier', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 900, 'Programmateur', NULL, 'http://id.loc.gov/vocabulary/relators/pro' );
INSERT INTO role ( id, label, creator, url ) VALUES( 910, 'Chef de la mission', NULL, 'http://id.loc.gov/vocabulary/relators/rth' );
INSERT INTO role ( id, label, creator, url ) VALUES( 980, 'Auteur ou responsable intellectuel (autre)', NULL, 'http://id.loc.gov/vocabulary/relators/aut' );
INSERT INTO role ( id, label, creator, url ) VALUES( 990, 'Auteur ou responsable intellectuel', NULL, 'http://id.loc.gov/vocabulary/relators/aut' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1010, 'Acteur', NULL, 'http://id.loc.gov/vocabulary/relators/act' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1020, 'Artiste de cirque', NULL, 'http://id.loc.gov/vocabulary/relators/prf' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1030, 'Chant', NULL, 'http://id.loc.gov/vocabulary/relators/sng' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1040, 'Direction d’orchestre', NULL, 'http://id.loc.gov/vocabulary/relators/cnd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1050, 'Marionnettiste', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 1060, 'Danse', NULL, 'http://id.loc.gov/vocabulary/relators/dnc' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1080, 'Direction de chœur', NULL, '	Chef de chœur' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1090, 'Mime', NULL, 'http://id.loc.gov/vocabulary/relators/prf' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1100, 'Instrumentiste', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1110, 'Voix parlée', NULL, 'http://id.loc.gov/vocabulary/relators/nrt' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1120, 'Soprano', NULL, 'http://id.loc.gov/vocabulary/relators/voc' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1130, 'Mezzo-soprano', NULL, 'http://id.loc.gov/vocabulary/relators/sng' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1140, 'Alto (voix)', NULL, 'http://id.loc.gov/vocabulary/relators/sng' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1150, 'Ténor', NULL, 'http://id.loc.gov/vocabulary/relators/sng' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1160, 'Baryton (voix)', NULL, 'http://id.loc.gov/vocabulary/relators/sng' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1170, 'Baryton-basse', NULL, 'http://id.loc.gov/vocabulary/relators/sng' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1180, 'Basse (voix)', NULL, 'http://id.loc.gov/vocabulary/relators/sng' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1190, 'Contre-ténor', NULL, 'http://id.loc.gov/vocabulary/relators/sng' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1200, 'Voix chantée d’enfant', NULL, 'http://id.loc.gov/vocabulary/relators/sng' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1210, 'Violon', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1220, 'Alto (instrument)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1230, 'Violoncelle', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1240, 'Contrebasse', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1250, 'Basse de viole', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1260, 'Viole d’amour', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1270, 'Harpe', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1280, 'Guitare', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1290, 'Guitare basse', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1300, 'Guitare hawaïenne', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1310, 'Luth', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1320, 'Théorbe', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1330, 'Mandoline', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1340, 'Vihuela', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1350, 'Banjo', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1360, 'Cithare', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1370, 'Cymbalum', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1380, 'Flûte', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1390, 'Piccolo', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1400, 'Flûte à bec', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1410, 'Flûte de Pan', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1420, 'Clarinette', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1430, 'Hautbois', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1440, 'Cor anglais', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1450, 'Saxophone', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1460, 'Basson', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1470, 'Trompette', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1480, 'Bugle', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1490, 'Cornet à pistons', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1500, 'Cornet à bouquin', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1510, 'Cor', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1520, 'Trombone', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1530, 'Tuba', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1540, 'Mirliton', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1550, 'Harmonica', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1560, 'Piano', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1570, 'Pianoforte', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1580, 'Clavecin', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1590, 'Orgue', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1600, 'Orgue mécanique', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1610, 'Harmonium', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1620, 'Clavicorde', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1630, 'Accordéon', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1640, 'Vielle à roue', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1650, 'Batterie', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1660, 'Tambour', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1670, 'Timbales', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1680, 'Xylophone', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1690, 'Marimba', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1700, 'Vibraphone', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1710, 'Carillon', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1720, 'Claquettes', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1730, 'Guimbarde', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1740, 'Harmonica de verre', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1750, 'Ondes Martenot', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1760, 'Synthétiseur', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1770, 'Instrument électronique (non autonome)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1780, 'Orchestre', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1790, 'Ensemble instrumental', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1800, 'Chœur mixte', NULL, 'http://id.loc.gov/vocabulary/relators/voc' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1810, 'Ensemble vocal', NULL, 'http://id.loc.gov/vocabulary/relators/voc' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1820, 'Ensemble vocal et instrumental', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1830, 'Siffleur', NULL, 'http://id.loc.gov/vocabulary/relators/prf' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1840, 'Bruitages', NULL, 'http://id.loc.gov/vocabulary/relators/prf' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1850, 'Disc jockey', NULL, 'http://id.loc.gov/vocabulary/relators/prf' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1860, 'Remixeur', NULL, 'http://id.loc.gov/vocabulary/relators/prf' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1870, 'Ensemble de cordes', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1880, 'Ensemble à vent', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1890, 'Ensemble de cuivres', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1900, 'Piano à 4 mains', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1910, 'Pianoforte à 4 mains', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1920, 'Célesta', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1930, 'Cornemuse', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1940, 'Washboard', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1980, 'Interprète (autre)', NULL, 'http://id.loc.gov/vocabulary/relators/prf' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1990, 'Interprète', NULL, 'http://id.loc.gov/vocabulary/relators/prf' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2010, 'Accessoiriste', NULL, 'http://id.loc.gov/vocabulary/relators/prd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2020, 'Assistant réalisateur', NULL, 'http://id.loc.gov/vocabulary/relators/prd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2030, 'Bruiteur', NULL, 'http://id.loc.gov/vocabulary/relators/rce' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2040, 'Cascades et batailles', NULL, 'http://id.loc.gov/vocabulary/relators/prd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2050, 'Coloriste', NULL, 'http://id.loc.gov/vocabulary/relators/prd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2060, 'Conseiller technique', NULL, 'http://id.loc.gov/vocabulary/relators/prd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2070, 'Contretypeur', NULL, '	Retirage d’après contretype' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2080, 'Costumes', NULL, 'http://id.loc.gov/vocabulary/relators/cst' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2090, 'Décors', NULL, 'http://id.loc.gov/vocabulary/relators/std' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2100, 'Directeur artistique', NULL, 'http://id.loc.gov/vocabulary/relators/drt' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2110, 'Directeur de ballet', NULL, 'http://id.loc.gov/vocabulary/relators/drt' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2120, 'Directeur musical', NULL, 'http://id.loc.gov/vocabulary/relators/drt' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2130, 'Documentaliste', NULL, 'http://id.loc.gov/vocabulary/relators/clb' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2140, 'Éclairages', NULL, 'http://id.loc.gov/vocabulary/relators/lgd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2150, 'Effets spéciaux', NULL, 'http://id.loc.gov/vocabulary/relators/prd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2160, 'Faussaire', NULL, 'http://id.loc.gov/vocabulary/relators/frg' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2170, 'Fondeur', NULL, 'http://id.loc.gov/vocabulary/relators/art' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2180, 'Illustration sonore', NULL, 'http://id.loc.gov/vocabulary/relators/rce' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2190, 'Maquettiste', NULL, 'http://id.loc.gov/vocabulary/relators/prd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2200, 'Maquillage', NULL, 'http://id.loc.gov/vocabulary/relators/prd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2210, 'Création des marionnettes', NULL, 'http://id.loc.gov/vocabulary/relators/ppt' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2220, 'Création des masques', NULL, 'http://id.loc.gov/vocabulary/relators/prd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2230, 'Montage', NULL, 'http://id.loc.gov/vocabulary/relators/flm' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2240, 'Photographe de plateau', NULL, 'http://id.loc.gov/vocabulary/relators/pht' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2250, 'Prises de vue', NULL, 'http://id.loc.gov/vocabulary/relators/pht' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2260, 'Régisseur', NULL, 'http://id.loc.gov/vocabulary/relators/prd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2270, 'Relieur', NULL, 'http://id.loc.gov/vocabulary/relators/bnd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2280, 'Scénographe', NULL, 'http://id.loc.gov/vocabulary/relators/rsg' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2290, 'Script', NULL, 'http://id.loc.gov/vocabulary/relators/prd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2300, 'Son', NULL, 'http://id.loc.gov/vocabulary/relators/rce' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2310, 'Typographe', NULL, 'http://id.loc.gov/vocabulary/relators/tyg' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2320, 'Régleur', NULL, 'http://id.loc.gov/vocabulary/relators/rbr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2330, 'Kitabdar', NULL, 'http://id.loc.gov/vocabulary/relators/mfr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2340, 'Scripteur', NULL, 'http://id.loc.gov/vocabulary/relators/trc' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2350, 'Cartonnage d’éditeur', NULL, 'http://id.loc.gov/vocabulary/relators/bjd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2360, 'Graphiste', NULL, 'http://id.loc.gov/vocabulary/relators/art' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2370, 'Régisseur son (théâtre)', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 2980, 'Contributeur technico-artistique (autre)', NULL, 'http://id.loc.gov/vocabulary/relators/prd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2990, 'Contributeur technico-artistique', NULL, 'http://id.loc.gov/vocabulary/relators/prd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3010, 'Commissaire-priseur', NULL, 'http://id.loc.gov/vocabulary/relators/auc' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3020, 'Détenteur du privilège', NULL, 'http://id.loc.gov/vocabulary/relators/les' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3030, 'Imprimeur-libraire antécédent', NULL, 'http://id.loc.gov/vocabulary/relators/bsl' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3040, 'Expert', NULL, 'http://id.loc.gov/vocabulary/relators/exp' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3050, 'Fabricant du papier', NULL, 'http://id.loc.gov/vocabulary/relators/ppm' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3060, 'Imprimeur', NULL, 'http://id.loc.gov/vocabulary/relators/prt' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3070, 'Laboratoire', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 3080, 'Producteur exécutif', NULL, 'http://id.loc.gov/vocabulary/relators/pro' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3090, 'Tireur de la photo', NULL, 'http://id.loc.gov/vocabulary/relators/pht' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3100, 'Agence de publicité', NULL, 'http://id.loc.gov/vocabulary/relators/pbl' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3110, 'Annonceur', NULL, 'http://id.loc.gov/vocabulary/relators/pbl' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3120, 'Commanditaire de la publication', NULL, 'http://id.loc.gov/vocabulary/relators/spn' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3130, 'Détenteur du copyright ou de protection', NULL, 'http://id.loc.gov/vocabulary/relators/cph' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3140, 'Directeur de production', NULL, 'http://id.loc.gov/vocabulary/relators/pro' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3150, 'Producteur', NULL, 'http://id.loc.gov/vocabulary/relators/pro' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3160, 'Producteur de phonogrammes', NULL, 'http://id.loc.gov/vocabulary/relators/pro' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3170, 'Producteur de vidéogrammes', NULL, 'http://id.loc.gov/vocabulary/relators/pro' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3180, 'Parrainage', NULL, 'http://id.loc.gov/vocabulary/relators/fnd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3190, 'Diffuseur', NULL, 'http://id.loc.gov/vocabulary/relators/dst' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3200, 'Directeur de salle de spectacle', NULL, 'http://id.loc.gov/vocabulary/relators/dst' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3210, 'Distributeur', NULL, 'http://id.loc.gov/vocabulary/relators/dst' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3220, 'Galerie', NULL, 'http://id.loc.gov/vocabulary/relators/dst' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3230, 'Agence de presse', NULL, 'http://id.loc.gov/vocabulary/relators/dst' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3240, 'Agence photographique', NULL, 'http://id.loc.gov/vocabulary/relators/dst' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3250, 'Éditeur commercial', NULL, 'http://id.loc.gov/vocabulary/relators/pbl' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3260, 'Imprimeur-libraire', NULL, 'http://id.loc.gov/vocabulary/relators/bsl' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3280, 'Libraire-marchand d’estampes', NULL, 'http://id.loc.gov/vocabulary/relators/bsl' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3290, 'Libraire', NULL, 'http://id.loc.gov/vocabulary/relators/bsl' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3300, 'Marchand', NULL, 'http://id.loc.gov/vocabulary/relators/bsl' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3310, 'Graveur de musique', NULL, 'http://id.loc.gov/vocabulary/relators/prm' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3320, 'Imprimeur de cartes', NULL, 'http://id.loc.gov/vocabulary/relators/prt' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3330, 'Parcheminier', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 3980, 'Opérateur commercial (autre)', NULL, 'http://id.loc.gov/vocabulary/relators/pbl' );
INSERT INTO role ( id, label, creator, url ) VALUES( 3990, 'Opérateur commercial', NULL, 'http://id.loc.gov/vocabulary/relators/pbl' );
INSERT INTO role ( id, label, creator, url ) VALUES( 4010, 'Ancien possesseur', NULL, 'http://id.loc.gov/vocabulary/relators/fmo' );
INSERT INTO role ( id, label, creator, url ) VALUES( 4020, 'Auteur de l’envoi', NULL, 'http://id.loc.gov/vocabulary/relators/aut' );
INSERT INTO role ( id, label, creator, url ) VALUES( 4030, 'Collectionneur', NULL, 'http://id.loc.gov/vocabulary/relators/col' );
INSERT INTO role ( id, label, creator, url ) VALUES( 4040, 'Donateur', NULL, 'http://id.loc.gov/vocabulary/relators/dnr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 4050, 'Doreur', NULL, 'http://id.loc.gov/vocabulary/relators/art' );
INSERT INTO role ( id, label, creator, url ) VALUES( 4060, 'Inventeur', NULL, 'http://id.loc.gov/vocabulary/relators/inv' );
INSERT INTO role ( id, label, creator, url ) VALUES( 4070, 'Parapheur', NULL, 'http://id.loc.gov/vocabulary/relators/sgn' );
INSERT INTO role ( id, label, creator, url ) VALUES( 4080, 'Destinataire de l’envoi', NULL, 'http://id.loc.gov/vocabulary/relators/rcp' );
INSERT INTO role ( id, label, creator, url ) VALUES( 4090, 'Ancien détenteur', NULL, 'http://id.loc.gov/vocabulary/relators/fmo' );
INSERT INTO role ( id, label, creator, url ) VALUES( 4100, 'Fondateur de waqf', NULL, 'http://id.loc.gov/vocabulary/relators/dnr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 4110, 'Administrateur de waqf', NULL, 'http://id.loc.gov/vocabulary/relators/dnr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 4120, 'Lecteur', NULL, 'http://id.loc.gov/vocabulary/relators/asn' );
INSERT INTO role ( id, label, creator, url ) VALUES( 4130, 'Musmi?', NULL, 'http://id.loc.gov/vocabulary/relators/asn' );
INSERT INTO role ( id, label, creator, url ) VALUES( 4140, 'Relieur', NULL, 'http://id.loc.gov/vocabulary/relators/bnd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 4150, 'Vendeur', NULL, 'http://id.loc.gov/vocabulary/relators/asn' );
INSERT INTO role ( id, label, creator, url ) VALUES( 4160, 'Bénéficiaire de waqf', NULL, 'http://id.loc.gov/vocabulary/relators/asn' );
INSERT INTO role ( id, label, creator, url ) VALUES( 4170, 'Annotations manuscrites', NULL, 'http://id.loc.gov/vocabulary/relators/ann' );
INSERT INTO role ( id, label, creator, url ) VALUES( 4180, 'Auteur de la pièce jointe', NULL, 'http://id.loc.gov/vocabulary/relators/wam' );
INSERT INTO role ( id, label, creator, url ) VALUES( 4190, 'Destinataire de la pièce jointe', NULL, 'http://id.loc.gov/vocabulary/relators/rcp' );
INSERT INTO role ( id, label, creator, url ) VALUES( 4200, 'Illustrateur de l’exemplaire', NULL, 'http://id.loc.gov/vocabulary/relators/ill' );
INSERT INTO role ( id, label, creator, url ) VALUES( 4210, 'Déposant', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 4220, 'Intermédiaire commercial', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 4230, 'Mécène', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 4240, 'Commanditaire de la reliure', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 4250, 'Dédicataire de la reliure', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 4260, 'Destinataire de la reliure', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 4270, 'Chromolithographe', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 4280, 'Emailleur', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 4290, 'Ivoirier', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 4300, 'Laqueur', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 4320, 'Papetier', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 4980, 'Intervenant sur l’exemplaire (autre)', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 4990, 'Intervenant sur l’exemplaire', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 5010, 'Lieu de représentation', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 5020, 'Lieu de copie', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 5030, 'Sujet', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 11, 'Adaptateur présumé', NULL, 'http://id.loc.gov/vocabulary/relators/adp' );
INSERT INTO role ( id, label, creator, url ) VALUES( 21, 'Agence de publicité présumée', NULL, 'http://id.loc.gov/vocabulary/relators/org' );
INSERT INTO role ( id, label, creator, url ) VALUES( 31, 'Agence photographique présumée', NULL, 'http://id.loc.gov/vocabulary/relators/org' );
INSERT INTO role ( id, label, creator, url ) VALUES( 41, 'Annotateur présumé', NULL, 'http://id.loc.gov/vocabulary/relators/ann' );
INSERT INTO role ( id, label, creator, url ) VALUES( 51, 'Arrangeur présumé', NULL, 'http://id.loc.gov/vocabulary/relators/arr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 71, 'Auteur présumé du texte', NULL, 'http://id.loc.gov/vocabulary/relators/att' );
INSERT INTO role ( id, label, creator, url ) VALUES( 81, 'Auteur présumé de l’argument', NULL, 'http://id.loc.gov/vocabulary/relators/lbt' );
INSERT INTO role ( id, label, creator, url ) VALUES( 91, 'Auteur présumé de l’animation', NULL, 'http://id.loc.gov/vocabulary/relators/anm' );
INSERT INTO role ( id, label, creator, url ) VALUES( 101, 'Auteur présumé de l’idée originale', NULL, 'http://id.loc.gov/vocabulary/relators/ccp' );
INSERT INTO role ( id, label, creator, url ) VALUES( 111, 'Auteur présumé de lettres', NULL, 'http://id.loc.gov/vocabulary/relators/att' );
INSERT INTO role ( id, label, creator, url ) VALUES( 121, 'Auteur présumé du commentaire', NULL, 'http://id.loc.gov/vocabulary/relators/cwt' );
INSERT INTO role ( id, label, creator, url ) VALUES( 141, 'Calligraphe supposé', NULL, 'http://id.loc.gov/vocabulary/relators/cll' );
INSERT INTO role ( id, label, creator, url ) VALUES( 151, 'Cartographe présumé', NULL, 'http://id.loc.gov/vocabulary/relators/ctg' );
INSERT INTO role ( id, label, creator, url ) VALUES( 161, 'Chorégraphe présumé', NULL, 'http://id.loc.gov/vocabulary/relators/chr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 171, 'Contributeur présumé', NULL, 'http://id.loc.gov/vocabulary/relators/clb' );
INSERT INTO role ( id, label, creator, url ) VALUES( 221, 'Compositeur présumé', NULL, 'http://id.loc.gov/vocabulary/relators/cmp' );
INSERT INTO role ( id, label, creator, url ) VALUES( 261, 'Continuateur présumé', NULL, 'http://id.loc.gov/vocabulary/relators/ctb' );
INSERT INTO role ( id, label, creator, url ) VALUES( 271, 'Copiste présumé', NULL, 'http://id.loc.gov/vocabulary/relators/scr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 311, 'Dessinateur présumé', NULL, 'http://id.loc.gov/vocabulary/relators/drm' );
INSERT INTO role ( id, label, creator, url ) VALUES( 321, 'Destinataire de lettres présumé', NULL, 'http://id.loc.gov/vocabulary/relators/rcp' );
INSERT INTO role ( id, label, creator, url ) VALUES( 341, 'Dialoguiste présumé', 1, 'http://id.loc.gov/vocabulary/relators/aud' );
INSERT INTO role ( id, label, creator, url ) VALUES( 411, 'Graveur présumé', NULL, 'http://id.loc.gov/vocabulary/relators/egr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 421, 'Graveur en lettres présumé', NULL, 'http://id.loc.gov/vocabulary/relators/egr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 441, 'Illustrateur présumé', 1, 'http://id.loc.gov/vocabulary/relators/ill' );
INSERT INTO role ( id, label, creator, url ) VALUES( 471, 'Librettiste présumé', 1, 'http://id.loc.gov/vocabulary/relators/lbt' );
INSERT INTO role ( id, label, creator, url ) VALUES( 481, 'Lithographe présumé', NULL, 'http://id.loc.gov/vocabulary/relators/ltg' );
INSERT INTO role ( id, label, creator, url ) VALUES( 521, 'Peintre présumé', NULL, 'http://id.loc.gov/vocabulary/relators/art' );
INSERT INTO role ( id, label, creator, url ) VALUES( 531, 'Photographe présumé', NULL, 'http://id.loc.gov/vocabulary/relators/pht' );
INSERT INTO role ( id, label, creator, url ) VALUES( 611, 'Réalisateur présumé', NULL, 'http://id.loc.gov/vocabulary/relators/rsg' );
INSERT INTO role ( id, label, creator, url ) VALUES( 641, 'Sculpteur présumé', NULL, 'http://id.loc.gov/vocabulary/relators/scl' );
INSERT INTO role ( id, label, creator, url ) VALUES( 711, 'Enlumineur présumé', NULL, 'http://id.loc.gov/vocabulary/relators/ilu' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1011, 'Acteur présumé', NULL, 'http://id.loc.gov/vocabulary/relators/act' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1031, 'Chanteur présumé', NULL, 'http://id.loc.gov/vocabulary/relators/sng' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1101, 'Instrumentiste présumé', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1651, 'Batterie (interprète présumé)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 4141, 'Collaborateur du relieur', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 72, 'Auteur adapté', NULL, 'http://id.loc.gov/vocabulary/relators/ant' );
INSERT INTO role ( id, label, creator, url ) VALUES( 152, 'Cartographe du modèle', NULL, 'http://id.loc.gov/vocabulary/relators/ctg' );
INSERT INTO role ( id, label, creator, url ) VALUES( 222, 'Compositeur de l’œuvre adaptée', NULL, 'http://id.loc.gov/vocabulary/relators/cmp' );
INSERT INTO role ( id, label, creator, url ) VALUES( 312, 'Dessinateur du modèle', NULL, 'http://id.loc.gov/vocabulary/relators/drm' );
INSERT INTO role ( id, label, creator, url ) VALUES( 412, 'Graveur du modèle', NULL, 'http://id.loc.gov/vocabulary/relators/egr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 422, 'Graveur en lettres du modèle', NULL, 'http://id.loc.gov/vocabulary/relators/egr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 522, 'Peintre du modèle', 1, 'http://id.loc.gov/vocabulary/relators/art' );
INSERT INTO role ( id, label, creator, url ) VALUES( 532, 'Photographe, auteur du modèle', NULL, 'http://id.loc.gov/vocabulary/relators/pht' );
INSERT INTO role ( id, label, creator, url ) VALUES( 642, 'Sculpteur du modèle', NULL, 'http://id.loc.gov/vocabulary/relators/scl' );
INSERT INTO role ( id, label, creator, url ) VALUES( 712, 'Enlumineur du modèle', NULL, 'http://id.loc.gov/vocabulary/relators/ilu' );
INSERT INTO role ( id, label, creator, url ) VALUES( 13, 'Adaptateur prétendu', NULL, 'http://id.loc.gov/vocabulary/relators/adp' );
INSERT INTO role ( id, label, creator, url ) VALUES( 23, 'Agence de publicité prétendue', NULL, 'http://id.loc.gov/vocabulary/relators/org' );
INSERT INTO role ( id, label, creator, url ) VALUES( 33, 'Agence photographique prétendue', NULL, 'http://id.loc.gov/vocabulary/relators/org' );
INSERT INTO role ( id, label, creator, url ) VALUES( 43, 'Annotateur prétendu', NULL, 'http://id.loc.gov/vocabulary/relators/ann' );
INSERT INTO role ( id, label, creator, url ) VALUES( 53, 'Arrangeur prétendu', NULL, 'http://id.loc.gov/vocabulary/relators/arr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 73, 'Auteur prétendu du texte', NULL, 'http://id.loc.gov/vocabulary/relators/dub' );
INSERT INTO role ( id, label, creator, url ) VALUES( 83, 'Auteur prétendu de l’argument', NULL, 'http://id.loc.gov/vocabulary/relators/lbt' );
INSERT INTO role ( id, label, creator, url ) VALUES( 93, 'Auteur prétendu de l’animation', NULL, 'http://id.loc.gov/vocabulary/relators/anm' );
INSERT INTO role ( id, label, creator, url ) VALUES( 103, 'Auteur prétendu de l’idée originale', NULL, 'http://id.loc.gov/vocabulary/relators/ccp' );
INSERT INTO role ( id, label, creator, url ) VALUES( 113, 'Auteur prétendu de lettres', NULL, 'http://id.loc.gov/vocabulary/relators/att' );
INSERT INTO role ( id, label, creator, url ) VALUES( 123, 'Auteur prétendu du commentaire', NULL, 'http://id.loc.gov/vocabulary/relators/cwt' );
INSERT INTO role ( id, label, creator, url ) VALUES( 143, 'Calligraphe prétendu', NULL, 'http://id.loc.gov/vocabulary/relators/cll' );
INSERT INTO role ( id, label, creator, url ) VALUES( 153, 'Cartographe prétendu', NULL, 'http://id.loc.gov/vocabulary/relators/ctg' );
INSERT INTO role ( id, label, creator, url ) VALUES( 163, 'Chorégraphe prétendu', NULL, 'http://id.loc.gov/vocabulary/relators/chr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 173, 'Contributeur prétendu', NULL, 'http://id.loc.gov/vocabulary/relators/clb' );
INSERT INTO role ( id, label, creator, url ) VALUES( 223, 'Compositeur prétendu', NULL, 'http://id.loc.gov/vocabulary/relators/cmp' );
INSERT INTO role ( id, label, creator, url ) VALUES( 263, 'Continuateur prétendu', NULL, 'http://id.loc.gov/vocabulary/relators/ctb' );
INSERT INTO role ( id, label, creator, url ) VALUES( 273, 'Copiste prétendu', NULL, 'http://id.loc.gov/vocabulary/relators/scr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 313, 'Dessinateur prétendu', NULL, 'http://id.loc.gov/vocabulary/relators/drm' );
INSERT INTO role ( id, label, creator, url ) VALUES( 343, 'Dialoguiste prétendu', 1, 'http://id.loc.gov/vocabulary/relators/aud' );
INSERT INTO role ( id, label, creator, url ) VALUES( 413, 'Graveur prétendu', NULL, 'http://id.loc.gov/vocabulary/relators/egr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 423, 'Graveur en lettres prétendu', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 443, 'Illustrateur prétendu', 1, 'http://id.loc.gov/vocabulary/relators/ill' );
INSERT INTO role ( id, label, creator, url ) VALUES( 473, 'Librettiste prétendu', 1, 'http://id.loc.gov/vocabulary/relators/lbt' );
INSERT INTO role ( id, label, creator, url ) VALUES( 483, 'Lithographe prétendu', NULL, 'http://id.loc.gov/vocabulary/relators/ltg' );
INSERT INTO role ( id, label, creator, url ) VALUES( 523, 'Peintre prétendu', NULL, 'http://id.loc.gov/vocabulary/relators/art' );
INSERT INTO role ( id, label, creator, url ) VALUES( 533, 'Photographe prétendu', NULL, 'http://id.loc.gov/vocabulary/relators/pht' );
INSERT INTO role ( id, label, creator, url ) VALUES( 613, 'Réalisateur prétendu', NULL, 'http://id.loc.gov/vocabulary/relators/rsg' );
INSERT INTO role ( id, label, creator, url ) VALUES( 643, 'Sculpteur prétendu', NULL, 'http://id.loc.gov/vocabulary/relators/scl' );
INSERT INTO role ( id, label, creator, url ) VALUES( 713, 'Enlumineur prétendu', NULL, 'http://id.loc.gov/vocabulary/relators/ilu' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1013, 'Acteur prétendu', NULL, 'http://id.loc.gov/vocabulary/relators/act' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1033, 'Chanteur prétendu', NULL, 'http://id.loc.gov/vocabulary/relators/sng' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1103, 'Instrumentiste prétendu', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1653, 'Batterie (interprète prétendu)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 24, 'Agence de publicité pour le document reproduit', NULL, 'http://id.loc.gov/vocabulary/relators/org' );
INSERT INTO role ( id, label, creator, url ) VALUES( 34, 'Agence photographique pour le document reproduit', NULL, 'http://id.loc.gov/vocabulary/relators/org' );
INSERT INTO role ( id, label, creator, url ) VALUES( 144, 'Calligraphe du document reproduit', NULL, 'http://id.loc.gov/vocabulary/relators/cll' );
INSERT INTO role ( id, label, creator, url ) VALUES( 154, 'Cartographe du document reproduit', NULL, 'http://id.loc.gov/vocabulary/relators/ctg' );
INSERT INTO role ( id, label, creator, url ) VALUES( 314, 'Dessinateur de l’œuvre reproduite', NULL, 'http://id.loc.gov/vocabulary/relators/drm' );
INSERT INTO role ( id, label, creator, url ) VALUES( 414, 'Graveur de l’œuvre reproduite', NULL, 'http://id.loc.gov/vocabulary/relators/egr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 424, 'Graveur en lettres de l’œuvre reproduite', NULL, 'http://id.loc.gov/vocabulary/relators/egr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 484, 'Lithographe de l’œuvre reproduite', NULL, 'http://id.loc.gov/vocabulary/relators/ltg' );
INSERT INTO role ( id, label, creator, url ) VALUES( 524, 'Peintre de l’œuvre reproduite', NULL, 'http://id.loc.gov/vocabulary/relators/art' );
INSERT INTO role ( id, label, creator, url ) VALUES( 534, 'Photographe de l’œuvre reproduite', NULL, 'http://id.loc.gov/vocabulary/relators/pht' );
INSERT INTO role ( id, label, creator, url ) VALUES( 644, 'Sculpteur de l’œuvre reproduite', NULL, 'http://id.loc.gov/vocabulary/relators/scl' );
INSERT INTO role ( id, label, creator, url ) VALUES( 714, 'Enlumineur de l’œuvre reproduite', NULL, 'http://id.loc.gov/vocabulary/relators/ilu' );
INSERT INTO role ( id, label, creator, url ) VALUES( 804, 'Auteur du slogan de l’œuvre reproduite', NULL, 'http://id.loc.gov/vocabulary/relators/ccp' );
INSERT INTO role ( id, label, creator, url ) VALUES( 365, 'Expert', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 485, 'Sérigraphe', NULL, 'http://id.loc.gov/vocabulary/relators/pop' );
INSERT INTO role ( id, label, creator, url ) VALUES( 505, 'Assistant metteur en scène', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 2045, 'Conseiller pour les cascades', NULL, 'http://id.loc.gov/vocabulary/relators/prd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2085, 'Chef costumier', NULL, 'http://id.loc.gov/vocabulary/relators/cst' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2095, 'Chef décorateur', NULL, 'http://id.loc.gov/vocabulary/relators/std' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2145, 'Conception des éclairages', NULL, '	Régisseur lumières' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2205, 'Chef maquilleur', NULL, 'http://id.loc.gov/vocabulary/relators/prd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2215, 'Conception des marionnettes', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 2235, 'Chef monteur image', NULL, 'http://id.loc.gov/vocabulary/relators/flm' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2255, 'Directeur de la photographie', NULL, 'http://id.loc.gov/vocabulary/relators/pht' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2305, 'Ingénieur du son', NULL, 'http://id.loc.gov/vocabulary/relators/rce' );
INSERT INTO role ( id, label, creator, url ) VALUES( 126, 'Auteur de la conférence', NULL, 'http://id.loc.gov/vocabulary/relators/aut' );
INSERT INTO role ( id, label, creator, url ) VALUES( 506, 'Direction du doublage', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 2046, 'Cascadeur', NULL, 'http://id.loc.gov/vocabulary/relators/prf' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2086, 'Réalisation des costumes', NULL, 'http://id.loc.gov/vocabulary/relators/cst' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2096, 'Ensemblier', NULL, 'http://id.loc.gov/vocabulary/relators/drt' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2146, 'Régisseur lumières', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 2206, 'Maquilleur', NULL, 'http://id.loc.gov/vocabulary/relators/prd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2216, 'Réalisation des marionnettes', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 2256, 'Opérateur prises de vue', NULL, 'http://id.loc.gov/vocabulary/relators/pht' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2266, 'Technicien régie', NULL, 'http://id.loc.gov/vocabulary/relators/prd' );
INSERT INTO role ( id, label, creator, url ) VALUES( 2306, 'Opérateur du son', NULL, 'http://id.loc.gov/vocabulary/relators/rce' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1017, 'Humoriste', NULL, 'http://id.loc.gov/vocabulary/relators/act' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1197, 'Haute-contre', NULL, 'http://id.loc.gov/vocabulary/relators/sng' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1217, 'Cordes frottées (divers)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1257, 'Viole', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1277, 'Harpes (diverses)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1287, 'Guitares (diverses)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1317, 'Luths (divers)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1337, 'Instruments à plectre (divers)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1357, 'Cordes pincées (divers)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1367, 'Cithares (diverses)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1377, 'Cordes frappées (divers)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1387, 'Bois (divers)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1407, 'Flûtes à bec (diverses)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1427, 'Instruments à anche (divers)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1437, 'Instruments à vent (divers)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1477, 'Cuivres (divers)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1527, 'Trombones (divers)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1537, 'Tubas (divers)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1557, 'Instruments à anche libre (divers)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1567, 'Claviers (divers)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1587, 'Clavecins (divers)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1597, 'Orgues (divers)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1607, 'Orgues mécaniques (divers)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1637, 'Accordéons (divers)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1657, 'Membranophones (divers)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1667, 'Percussions', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1707, 'Métallophones (divers)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1717, 'Idiophones par percussion (divers)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1747, 'Cristallophones', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1767, 'Instrument électronique', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1777, 'Sculptures et environnements sonores', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1787, 'Ensembles (divers)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1797, 'Groupe instrumental', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1807, 'Chœur à voix égales', NULL, 'http://id.loc.gov/vocabulary/relators/voc' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1817, 'Groupe vocal', NULL, 'http://id.loc.gov/vocabulary/relators/voc' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1827, 'Groupe vocal et instrumental', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1837, 'Bruits corporels', NULL, 'http://id.loc.gov/vocabulary/relators/prf' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1937, 'Cornemuses (diverses)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1947, 'Idiophones raclés (divers)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 9997, 'Absent', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 1018, 'Chansonnier', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 1108, 'Instrumentiste (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1218, 'Cordes frottées (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1258, 'Cordophones divers (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1268, 'Hardingfele', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1278, 'Harpes (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1288, 'Guitares (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1318, 'Luths (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1358, 'Cordes pincées (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1368, 'Cithares (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1378, 'Cordes frappées (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1388, 'Flûtes (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1418, 'Flûtes de Pan (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1428, 'Instruments à anche (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1438, 'Instruments à vent divers (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1478, 'Trompes (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1558, 'Instruments à anche libre (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1598, 'Orgue (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1638, 'Accordéon (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1658, 'Membranophones (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1668, 'Percussions (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1688, 'Xylophones (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1718, 'Idiophones par percussion (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1728, 'Idiophones secoués (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1738, 'Idiophones pincés (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1748, 'Idiophones frottés (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1798, 'Ensemble instrumental (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1818, 'Ensemble vocal (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/voc' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1828, 'Ensemble vocal et instrumental (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1878, 'Ensemble de cordes (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1888, 'Ensemble à vent (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1898, 'Ensemble de cuivres (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1938, 'Cornemuses (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1948, 'Idiophones raclés (musique ethnique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 9998, 'Littéral', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 1039, 'Chant (sons traités par l’électronique)', NULL, 'http://id.loc.gov/vocabulary/relators/sng' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1119, 'Voix parlée (sons traités par l’électronique)', NULL, 'http://id.loc.gov/vocabulary/relators/nrt' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1129, 'Soprano (sons traités par l’électronique)', NULL, 'http://id.loc.gov/vocabulary/relators/sng' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1139, 'Mezzo-soprano (sons traités par l’électronique)', NULL, 'http://id.loc.gov/vocabulary/relators/sng' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1149, 'Alto (voix ; sons traités par l’électronique)', NULL, 'http://id.loc.gov/vocabulary/relators/sng' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1159, 'Ténor (sons traités par l’électronique)', NULL, 'http://id.loc.gov/vocabulary/relators/sng' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1169, 'Baryton (voix ; sons traités par l’électronique)', NULL, 'http://id.loc.gov/vocabulary/relators/sng' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1179, 'Baryton-basse (sons traités par l’électronique)', NULL, 'http://id.loc.gov/vocabulary/relators/sng' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1189, 'Basse (voix ; sons traités par l’électronique)', NULL, 'http://id.loc.gov/vocabulary/relators/sng' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1199, 'Contre-ténor (sons traités par l’électronique)', NULL, 'http://id.loc.gov/vocabulary/relators/sng' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1219, 'Violon électrique', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1229, 'Alto (instrument ; traité par l’électronique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1239, 'Violoncelle électrique', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1249, 'Contrebasse électrique', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1289, 'Guitare électrique', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1299, 'Guitare basse électrique', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1309, 'Pedal steel guitar', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1389, 'Flûte (sons traités par l’électronique)', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1459, 'Lyricon', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1569, 'Piano électrique', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1599, 'Orgue électronique', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1649, 'Vielle à roue électrique', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 1659, 'Batterie électrique', NULL, 'http://id.loc.gov/vocabulary/relators/itr' );
INSERT INTO role ( id, label, creator, url ) VALUES( 9999, 'Inconnu', NULL, NULL );
INSERT INTO role ( id, label, creator, url ) VALUES( 70, 'Auteur du texte', NULL, 'http://id.loc.gov/vocabulary/relators/aut' );
INSERT INTO role ( id, label, creator, url ) VALUES( 9990, 'Autre', NULL, NULL );
